# Generated by Django 4.1.4 on 2022-12-12 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(max_length=255, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('sku', models.CharField(max_length=255, unique=True, verbose_name='sku')),
                ('slug', models.SlugField(max_length=255, verbose_name='slug')),
                ('status', models.CharField(choices=[('in_stock', 'in stock'), ('on_order', 'on order'), ('waiting', 'waiting'), ('not_in_stock', 'not in stock'), ('not_making', 'not making')], max_length=255, verbose_name='status')),
                ('img', models.ImageField(upload_to='media/images/product')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='testshop.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PropertyObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('code', models.SlugField(max_length=255, verbose_name='code')),
                ('value_type', models.CharField(choices=[('string', 'string'), ('decimal', 'decimal')], max_length=10, verbose_name='value type')),
            ],
            options={
                'verbose_name': 'property object',
                'verbose_name_plural': 'properties objects',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PropertyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_string', models.CharField(blank=True, max_length=255, null=True, verbose_name='value string')),
                ('value_decimal', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='value decimal')),
                ('code', models.SlugField(max_length=255, verbose_name='code')),
                ('products', models.ManyToManyField(related_name='properties', to='testshop.product')),
                ('property_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testshop.propertyobject')),
            ],
            options={
                'verbose_name': 'property value',
                'verbose_name_plural': 'properties values',
                'ordering': ['value_string', 'value_decimal'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='property_objects',
            field=models.ManyToManyField(to='testshop.propertyobject', verbose_name='properties'),
        ),
    ]
