# Generated by Django 4.1.4 on 2022-12-13 00:08

from django.db import migrations
import testshop.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=testshop.fields.WEBPField(default=None, upload_to='media/images/product'),
        ),
    ]
