# Generated by Django 4.1.4 on 2022-12-13 00:10

from django.db import migrations
import testshop.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testshop', '0002_remove_product_img_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=testshop.fields.WEBPField(default=None, upload_to='images/product'),
        ),
    ]
