# Generated by Django 4.1.4 on 2022-12-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testshop', '0005_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, default='0.00', max_digits=10, verbose_name='price'),
        ),
    ]
